development:
  adapter:  postgresql
  encoding: unicode
  database: rssyeah_dev
  pool:     5
  timeout:  5000
  username: rssyeah
  password:

test:
  adapter:  postgresql
  encoding: unicode
  database: rssyeah_test
  pool:     5
  timeout:  5000
  username: rssyeah
  password:

production:
  adapter:   postgresql
  encoding:  unicode
  database:  rssyeah_prod
  host:      localhost
  pool:      5
  timeout:   5000
  username:  rssyeah
  password:  yeahbaby

